# Python CircleCI 2.0 configuration file
# References
# - https://circleci.com/docs/2.0/project-walkthrough/
# - https://circleci.com/docs/2.0/language-python/

version: 2

jobs:
  build:
    # Primary container
    docker:
      # Python3.8 image with web browsers added
      - image: circleci/python:3.8
        # Important environment variables are located on the Project Settings of CircleCI
        environment:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1

      # - image: circleci/postgres:11.3
      # - image: circleci/redis:5.0

    working_directory: ~/bookstore-base-project

    steps:
      # Step 1: Obtain repo from Github
      - checkout

      # Step 2: Grant permission to CircleCI to grant access to dependency locations
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages

      # Step 3: Restore cache corresponded to this specific key using Pipfile.lock checksum
      - restore_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      # Step 4: Install Pipenv and then dependencies
      - run:
          name: Install python dependencies
          command: |
            pip install pipenv && pipenv install --system

      # Step 5: Save cache for future implementation
      - save_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"

  lint:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/bookstore-base-project

    steps:
      # Step 1: Obtain repo from Github
      - checkout

      # Step 2: Grant permission to CircleCI to grant access to dependency locations
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages

      # Step 3: Restore cache corresponded to this specific key using Pipfile.lock checksum
      - restore_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      # Step 4: Run linter
      - run:
        name: Run linter
        command: |
          pipenv run pylint bookstore-base-project

      # Step 5: Run code formatter
      - run:
        name: Run code formatter
        command: |
          pipenv run black bookstore-base-project

      # Step 6: Run type checker
      - run:
        name: Run type checker
        command: |
          pipenv run mypy bookstore-base-project

  test:
    docker:
      - image: circleci/python:3.8-browsers

    working_directory: ~/bookstore-base-project

    steps:
      # Step 1: Obtain repo from Github
      - checkout

      # Step 2: Grant permission to CircleCI to grant access to dependency locations
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages

      # Step 3: Restore cache corresponded to this specific key using Pipfile.lock checksum
      - restore_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock "}}

      # Step 4: Run unit tests
      - run:
          name: Run unit tests
          command: |
            pipenv run python manage.py test

      # Step 5: Run test coverage report
      - run:
          name: Run test coverage report
          command: |
            pipenv run coverage run -m pytest

      # Step 6: Store test results
      - store_test_results:
          path: test-results/

      # Step 7: Store artifacts
      - store_artifacts:
          path: test-results/
          destination: tr1

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - lint
      - test
